## docker buildx build . -t openttdv2
FROM ghcr.io/linuxserver/baseimage-ubuntu:jammy

# set version label
ARG BUILD_DATE
# renovate: datasource=github-releases depName=OpenTTD/OpenTTD
ARG OPENTTD_VERSION="14.0"
# renovate: datasource=github-releases depName=OpenTTD/OpenGFX
ARG OPENGFX_VERSION="7.0"

LABEL build_version="version:- ${VERSION} Build-date:- ${BUILD_DATE}"
LABEL maintainer="flappje"

# environment settings
ENV \
  LOAD_ORDER = "last,auto_save,exit,save_file" \
  SAVE_FILE = "" \
  SAVE_CONFIG_ON_EXIT=true\
  DEBUG = 0

RUN \
  echo "**** install packages ****" && \
  apt-get update && \
  apt-get install -y --no-install-recommends \
    wget \
    unzip \
    xz-utils \
    libfontconfig1 \
    libfreetype6 \
    libfluidsynth3 \
    libicu-dev \
    libpng16-16 \
    liblzma-dev \
    liblzo2-2 \
    libsdl1.2debian \
    libsdl2-2.0-0 && \
    \
    \
  echo "**** install openttd ****" && \
  mkdir -p /usr/games/openttd && \
  curl -o \
    /tmp/openttd.tar.xz -L \
    "https://cdn.openttd.org/openttd-releases/${OPENTTD_VERSION}/openttd-${OPENTTD_VERSION}-linux-generic-amd64.tar.xz" && \
  tar xf \
    /tmp/openttd.tar.xz -C \
    /usr/games/openttd --strip-components=1 && \
    \
    \
  echo "**** install opengfx ****" && \
  curl -o \
    /tmp/opengfx.zip -L \
    "https://cdn.openttd.org/opengfx-releases/${OPENGFX_VERSION}/opengfx-${OPENGFX_VERSION}-all.zip" && \
  unzip -p \
    /tmp/opengfx.zip \
    | tar xf - -C /usr/games/openttd/baseset --strip-components=1 && \
    \
    \
  echo "**** cleanup ****" && \
  apt-get -y remove unzip wget xz-utils && \
  apt-get clean && \
  rm -rf \
    /tmp/* \
    /var/lib/apt/lists/* \
    /var/tmp/*

# add local files
COPY root/ /

# ports and volumes
EXPOSE 3978/udp
EXPOSE 3979 
EXPOSE 3979/udp 

VOLUME /config
