services:
  openttd:
    container_name: openttd
    image: flappje/openttd
    restart: unless-stopped
    volumes:
      - ./openttd:/openttd
    ports:
      - 3979:3979/tcp
      - 3979:3979/udp
    #environment:
      #- "loadgame=last-autosave"
      #- "savepath=/home/openttd/.openttd/save"
